
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__sessionadapter_h__adaptor__H__
#define __sdbuscpp__sessionadapter_h__adaptor__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace freedesktop {
namespace Secret {

class Session_adaptor
{
public:
    static constexpr const char* INTERFACE_NAME = "org.freedesktop.Secret.Session";

protected:
    Session_adaptor(sdbus::IObject& object)
        : object_(object)
    {

    }

    ~Session_adaptor() = default;


private:
    sdbus::IObject& object_;
};

}}} // namespaces

#endif
